### ISSUE TITLE
Trying to hook openat syscall

### ISSUE THREAD

**Issue by akrogames** [Conviso-Archives/openhook#1]
Hi Victor,

Hope you are well. I am trying to hook openat syscall with your source code but there are an issue. Can you try with me ?

I thought that was an issue with kernel memory protection but my solution doesn't work.

Errors Logs : 

> [Mon Apr 27 20:57:31 2020] isds-tde : Dans mon SYS_OPEN !!!
> [Mon Apr 27 20:57:31 2020] BUG: unable to handle page fault for address: 0000000040ef7fb8
> [Mon Apr 27 20:57:31 2020] #PF: supervisor read access in kernel mode
> [Mon Apr 27 20:57:31 2020] #PF: error_code(0x0000) - not-present page
> [Mon Apr 27 20:57:31 2020] PGD 0 P4D 0 
> [Mon Apr 27 20:57:31 2020] Oops: 0000 [#1] SMP PTI
> [Mon Apr 27 20:57:31 2020] CPU: 1 PID: 2390 Comm: sudo Tainted: G           OE     5.3.0-46-generic #38~18.04.1-Ubuntu
> [Mon Apr 27 20:57:31 2020] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.10.2-1ubuntu1 04/01/2014
> [Mon Apr 27 20:57:31 2020] RIP: 0010:__x64_sys_openat+0x6/0x30
> [Mon Apr 27 20:57:31 2020] Code: 60 8b 77 28 bf 9c ff ff ff 48 89 e5 80 ce 80 e8 d0 fc ff ff 5d c3 0f 1f 40 00 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 55 <8b> 57 60 0f b7 4f 38 48 8b 77 68 48 8b 7f 70 48 89 e5 80 ce 80 e8
> [Mon Apr 27 20:57:31 2020] RSP: 0018:ffffa69540ef7ef8 EFLAGS: 00010286
> [Mon Apr 27 20:57:31 2020] RAX: ffffffffbcccb7b0 RBX: 0000000000000000 RCX: 0000000000000000
> [Mon Apr 27 20:57:31 2020] RDX: 0000000000000000 RSI: ffffa69540ef7f58 RDI: 0000000040ef7f58
> [Mon Apr 27 20:57:31 2020] RBP: ffffa69540ef7f28 R08: 000000000000027f R09: 0000000000000004
> [Mon Apr 27 20:57:31 2020] R10: 0000000000000000 R11: 0000000000000001 R12: 0000000040ef7f58
> [Mon Apr 27 20:57:31 2020] R13: ffffa69540ef7f58 R14: 0000000000000000 R15: 0000000000000000
> [Mon Apr 27 20:57:31 2020] FS:  00007f971999ac80(0000) GS:ffff985abba80000(0000) knlGS:0000000000000000
> [Mon Apr 27 20:57:31 2020] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
> [Mon Apr 27 20:57:31 2020] CR2: 0000000040ef7fb8 CR3: 0000000131d2c001 CR4: 00000000003606e0
> [Mon Apr 27 20:57:31 2020] Call Trace:
> [Mon Apr 27 20:57:31 2020]  ? openat_hook+0x3f/0x50 [openhook]
> [Mon Apr 27 20:57:31 2020]  do_syscall_64+0x5a/0x130
> [Mon Apr 27 20:57:31 2020]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
> [Mon Apr 27 20:57:31 2020] RIP: 0033:0x7f9718c35c8e
> [Mon Apr 27 20:57:31 2020] Code: 25 00 00 41 00 3d 00 00 41 00 74 48 48 8d 05 81 0c 2e 00 8b 00 85 c0 75 69 89 f2 b8 01 01 00 00 48 89 fe bf 9c ff ff ff 0f 05 <48> 3d 00 f0 ff ff 0f 87 a6 00 00 00 48 8b 4c 24 28 64 48 33 0c 25
> [Mon Apr 27 20:57:31 2020] RSP: 002b:00007ffcd012b820 EFLAGS: 00000246 ORIG_RAX: 0000000000000101
> [Mon Apr 27 20:57:31 2020] RAX: ffffffffffffffda RBX: 0000557daae1c260 RCX: 00007f9718c35c8e
> [Mon Apr 27 20:57:31 2020] RDX: 0000000000000000 RSI: 00007f9716b165ba RDI: 00000000ffffff9c
> [Mon Apr 27 20:57:31 2020] RBP: 00007f9716b15f77 R08: 0000000000000000 R09: 0000000000000000
> [Mon Apr 27 20:57:31 2020] R10: 0000000000000000 R11: 0000000000000246 R12: 0000000000000008
> [Mon Apr 27 20:57:31 2020] R13: 00007f9716b15f77 R14: 00007f9716b165ce R15: 0000000000000000
> [Mon Apr 27 20:57:31 2020] Modules linked in: openhook(OE) intel_rapl_msr snd_hda_codec_generic ledtrig_audio snd_hda_intel snd_intel_nhlt intel_rapl_common snd_hda_codec snd_hda_core input_leds snd_hwdep joydev snd_pcm serio_raw snd_timer snd soundcore mac_hid qemu_fw_cfg sch_fq_codel ib_iser rdma_cm iw_cm ib_cm ib_core iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi ip_tables x_tables autofs4 btrfs zstd_compress raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear hid_generic usbhid hid crct10dif_pclmul crc32_pclmul ghash_clmulni_intel qxl ttm drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops aesni_intel drm virtio_net aes_x86_64 crypto_simd net_failover cryptd i2c_piix4 glue_helper failover psmouse virtio_blk pata_acpi floppy [last unloaded: openhook]

New source code : 
```
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/unistd.h>
#include <asm/pgtable.h>
#include <linux/slab.h>
#include <linux/syscalls.h>

unsigned long cr0;
static unsigned long *sys_call_table;
typedef asmlinkage long (*orig_open_t)(const char *, int, mode_t);
orig_open_t orig_open;

// SYS_OPENAT hooking
// asmlinkage long sys_openat(int dfd, const char __user *filename, int flags, umode_t mode);
typedef asmlinkage long (*original_sys_openat)(int, const char *, int, umode_t);
original_sys_openat orig_openat;

#define START_MEM	PAGE_OFFSET
#define END_MEM		ULONG_MAX

unsigned long *
get_syscall_table_bf(void)
{
	unsigned long *syscall_table;
	unsigned long int i;

	i = kallsyms_lookup_name("sys_call_table");
	if (i == 0) {
	    return NULL;
	}
	syscall_table = (unsigned long*)i;
	return syscall_table;
}

/* sys_open hook */
asmlinkage static int hacked_open(const char __user *pathname, int flags, mode_t mode)
{
	printk(KERN_INFO "sys_open() hook!\n");
	return orig_open(pathname, flags, mode);
}

asmlinkage long openat_hook(int fds, const char *filename, int flags, umode_t mode) {
    printk(KERN_INFO "isds-tde : Dans mon SYS_OPEN !!!\n");

		return orig_openat(fds, filename, flags, mode);
}

inline void mywrite_cr0(unsigned long cr0) {
  asm volatile("mov %0,%%cr0" : "+r"(cr0), "+m"(__force_order));
}

static inline void protect_memory(void)
{
	unsigned long cr0 = read_cr0();
	set_bit(16, &cr0);
	mywrite_cr0(cr0);
//	write_cr0(cr0);
}

static inline void unprotect_memory(void)
{
	unsigned long cr0 = read_cr0();
	clear_bit(16, &cr0);
	mywrite_cr0(cr0);
//	write_cr0(cr0 & ~0x00010000);
}

static int __init syshook_init(void)
{

	sys_call_table = (unsigned long *)get_syscall_table_bf();

	if (!sys_call_table) {
		printk(KERN_INFO "sys_call_table not found");
		return -1;
	}

	cr0 = read_cr0();

	orig_open = (orig_open_t)sys_call_table[__NR_open];
	orig_openat = (original_sys_openat)sys_call_table[__NR_openat];

	unprotect_memory();
	sys_call_table[__NR_open] = (unsigned long)hacked_open;
	sys_call_table[__NR_openat] = (unsigned long)openat_hook;
	protect_memory();


	return 0;
}

static void __exit
syshook_cleanup(void)
{
	if (orig_open) {
		unprotect_memory();
		sys_call_table[__NR_open] = (unsigned long)orig_open;
		sys_call_table[__NR_openat] = (unsigned long)orig_openat;
		protect_memory();
	}

}

module_init(syshook_init);
module_exit(syshook_cleanup);

MODULE_LICENSE("Dual BSD/GPL");
MODULE_AUTHOR("Victor Ramos Mello");
MODULE_DESCRIPTION("A sys_call_table hooking example");
```

**Comment by m0nad** [comment]
Openhook is no longer maintained and was made before kernel 5.3.0. A project that may help you with is this one https://github.com/milabs/khook

**Comment by akrogames** [comment]
Thanks for your reply :) Unfortunately, KHook has the same issue on openat syscall. I will close this issue. Thanks again.

Just for info with KHook.
```
KHOOK_EXT(long, __x64_sys_openat, int fds, const char *filename, int flags, umode_t mode);
static long khook___x64_sys_openat(int fds, const char *filename, int flags, umode_t mode) {
        printk("sys_openat -- %s\n", filename);
        return KHOOK_ORIGIN(__x64_sys_openat, fds, filename, flags, mode);
}
```

Log : 
> [Tue Apr 28 10:21:51 2020] BUG: unable to handle page fault for address: 0000000080e23fb8
> [Tue Apr 28 10:21:51 2020] #PF: supervisor read access in kernel mode
> [Tue Apr 28 10:21:51 2020] #PF: error_code(0x0000) - not-present page
